//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OurResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OurResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrystalEditor.OurResources", typeof(OurResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string ActionLabel {
            get {
                return ResourceManager.GetString("ActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ActionsNodeLabel {
            get {
                return ResourceManager.GetString("ActionsNodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &quot;{0}&quot; tag.
        /// </summary>
        public static string AddTagLabel {
            get {
                return ResourceManager.GetString("AddTagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string AlwaysConditionLabel {
            get {
                return ResourceManager.GetString("AlwaysConditionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And.
        /// </summary>
        public static string BinaryLogicKind_And {
            get {
                return ResourceManager.GetString("BinaryLogicKind_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or.
        /// </summary>
        public static string BinaryLogicKind_Or {
            get {
                return ResourceManager.GetString("BinaryLogicKind_Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =.
        /// </summary>
        public static string CompareKind_Equals {
            get {
                return ResourceManager.GetString("CompareKind_Equals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;.
        /// </summary>
        public static string CompareKind_GreaterThan {
            get {
                return ResourceManager.GetString("CompareKind_GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;=.
        /// </summary>
        public static string CompareKind_GreaterThanOrEqual {
            get {
                return ResourceManager.GetString("CompareKind_GreaterThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;.
        /// </summary>
        public static string CompareKind_LessThan {
            get {
                return ResourceManager.GetString("CompareKind_LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;=.
        /// </summary>
        public static string CompareKind_LessThanOrEqual {
            get {
                return ResourceManager.GetString("CompareKind_LessThanOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition:.
        /// </summary>
        public static string ConditionHeaderLabel {
            get {
                return ResourceManager.GetString("ConditionHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On conflict:.
        /// </summary>
        public static string ConflictResolutionHeaderLabel {
            get {
                return ResourceManager.GetString("ConflictResolutionHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy &quot;{0}&quot; tag to &quot;{1}&quot;.
        /// </summary>
        public static string CopyTagLabel {
            get {
                return ResourceManager.GetString("CopyTagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects:.
        /// </summary>
        public static string EffectsHeaderLabel {
            get {
                return ResourceManager.GetString("EffectsHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacker.
        /// </summary>
        public static string EffectTarget_Attacker {
            get {
                return ResourceManager.GetString("EffectTarget_Attacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacker&apos;s actions.
        /// </summary>
        public static string EffectTarget_AttackerActions {
            get {
                return ResourceManager.GetString("EffectTarget_AttackerActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacker&apos;s selected action.
        /// </summary>
        public static string EffectTarget_AttackerSelectedAction {
            get {
                return ResourceManager.GetString("EffectTarget_AttackerSelectedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender.
        /// </summary>
        public static string EffectTarget_Defender {
            get {
                return ResourceManager.GetString("EffectTarget_Defender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender&apos;s actions.
        /// </summary>
        public static string EffectTarget_DefenderActions {
            get {
                return ResourceManager.GetString("EffectTarget_DefenderActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender&apos;s selected action.
        /// </summary>
        public static string EffectTarget_DefenderSelectedAction {
            get {
                return ResourceManager.GetString("EffectTarget_DefenderSelectedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary workspace.
        /// </summary>
        public static string EffectTarget_TemporaryWorkspace {
            get {
                return ResourceManager.GetString("EffectTarget_TemporaryWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Rules.
        /// </summary>
        public static string GameRulesLabel {
            get {
                return ResourceManager.GetString("GameRulesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has tag.
        /// </summary>
        public static string HasTagConditionLabel {
            get {
                return ResourceManager.GetString("HasTagConditionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string KeyConflictResolutionKind_Add {
            get {
                return ResourceManager.GetString("KeyConflictResolutionKind_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep all.
        /// </summary>
        public static string KeyConflictResolutionKind_KeepAll {
            get {
                return ResourceManager.GetString("KeyConflictResolutionKind_KeepAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep larger.
        /// </summary>
        public static string KeyConflictResolutionKind_KeepLarger {
            get {
                return ResourceManager.GetString("KeyConflictResolutionKind_KeepLarger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep smaller.
        /// </summary>
        public static string KeyConflictResolutionKind_KeepSmaller {
            get {
                return ResourceManager.GetString("KeyConflictResolutionKind_KeepSmaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string KeyConflictResolutionKind_Replace {
            get {
                return ResourceManager.GetString("KeyConflictResolutionKind_Replace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtract.
        /// </summary>
        public static string KeyConflictResolutionKind_Subtract {
            get {
                return ResourceManager.GetString("KeyConflictResolutionKind_Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key:.
        /// </summary>
        public static string KeyHeaderLabel {
            get {
                return ResourceManager.GetString("KeyHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key match kind:.
        /// </summary>
        public static string KeyMatchKindHeaderLabel {
            get {
                return ResourceManager.GetString("KeyMatchKindHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match key:.
        /// </summary>
        public static string MatchKeyHeaderLabel {
            get {
                return ResourceManager.GetString("MatchKeyHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contains.
        /// </summary>
        public static string MatchKind_Contains {
            get {
                return ResourceManager.GetString("MatchKind_Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact.
        /// </summary>
        public static string MatchKind_Exact {
            get {
                return ResourceManager.GetString("MatchKind_Exact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string MatchKind_Prefix {
            get {
                return ResourceManager.GetString("MatchKind_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reg. exp..
        /// </summary>
        public static string MatchKind_Regex {
            get {
                return ResourceManager.GetString("MatchKind_Regex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix.
        /// </summary>
        public static string MatchKind_Suffix {
            get {
                return ResourceManager.GetString("MatchKind_Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match scopes:.
        /// </summary>
        public static string MatchScopesHeaderLabel {
            get {
                return ResourceManager.GetString("MatchScopesHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string NameHeaderLabel {
            get {
                return ResourceManager.GetString("NameHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string NeverConditionLabel {
            get {
                return ResourceManager.GetString("NeverConditionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add action.
        /// </summary>
        public static string NewActionLabel {
            get {
                return ResourceManager.GetString("NewActionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tag.
        /// </summary>
        public static string NewAddTagLabel {
            get {
                return ResourceManager.GetString("NewAddTagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy tag.
        /// </summary>
        public static string NewCopyTagLabel {
            get {
                return ResourceManager.GetString("NewCopyTagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove tag.
        /// </summary>
        public static string NewRemoveTagLabel {
            get {
                return ResourceManager.GetString("NewRemoveTagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add result.
        /// </summary>
        public static string NewResultLabel {
            get {
                return ResourceManager.GetString("NewResultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tag key:.
        /// </summary>
        public static string NewTagKeyHeaderLabel {
            get {
                return ResourceManager.GetString("NewTagKeyHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Battle Effects.
        /// </summary>
        public static string PostBattleEffectsNodeLabel {
            get {
                return ResourceManager.GetString("PostBattleEffectsNodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Result Effects.
        /// </summary>
        public static string PostResultEffectsNodelLabel {
            get {
                return ResourceManager.GetString("PostResultEffectsNodelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Turn Effects.
        /// </summary>
        public static string PostTurnEffectsNodeLabel {
            get {
                return ResourceManager.GetString("PostTurnEffectsNodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Battle Effects.
        /// </summary>
        public static string PreBattleEffectsNodeLabel {
            get {
                return ResourceManager.GetString("PreBattleEffectsNodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Result Effects.
        /// </summary>
        public static string PreResultEffectsNodeLabel {
            get {
                return ResourceManager.GetString("PreResultEffectsNodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Turn Effects.
        /// </summary>
        public static string PreTurnEffectsNodeLabel {
            get {
                return ResourceManager.GetString("PreTurnEffectsNodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove &quot;{0}&quot; tag.
        /// </summary>
        public static string RemoveTagLabel {
            get {
                return ResourceManager.GetString("RemoveTagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        public static string ResultLabel {
            get {
                return ResourceManager.GetString("ResultLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        public static string ResultsNodeLabel {
            get {
                return ResourceManager.GetString("ResultsNodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag:.
        /// </summary>
        public static string TagHeaderLabel {
            get {
                return ResourceManager.GetString("TagHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag key:.
        /// </summary>
        public static string TagKeyHeaderLabel {
            get {
                return ResourceManager.GetString("TagKeyHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match:.
        /// </summary>
        public static string TagKeyMatchKindHeaderLabel {
            get {
                return ResourceManager.GetString("TagKeyMatchKindHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacker.
        /// </summary>
        public static string TagScope_Attacker {
            get {
                return ResourceManager.GetString("TagScope_Attacker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacker&apos;s action.
        /// </summary>
        public static string TagScope_AttackerAction {
            get {
                return ResourceManager.GetString("TagScope_AttackerAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attacker&apos;s result.
        /// </summary>
        public static string TagScope_AttackerResult {
            get {
                return ResourceManager.GetString("TagScope_AttackerResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle.
        /// </summary>
        public static string TagScope_Battle {
            get {
                return ResourceManager.GetString("TagScope_Battle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current action.
        /// </summary>
        public static string TagScope_CurrentAction {
            get {
                return ResourceManager.GetString("TagScope_CurrentAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender.
        /// </summary>
        public static string TagScope_Defender {
            get {
                return ResourceManager.GetString("TagScope_Defender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender&apos;s action.
        /// </summary>
        public static string TagScope_DefenderAction {
            get {
                return ResourceManager.GetString("TagScope_DefenderAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defender&apos;s result.
        /// </summary>
        public static string TagScope_DefenderResult {
            get {
                return ResourceManager.GetString("TagScope_DefenderResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string TagScope_None {
            get {
                return ResourceManager.GetString("TagScope_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary workspace.
        /// </summary>
        public static string TagScope_TemporaryWorkspace {
            get {
                return ResourceManager.GetString("TagScope_TemporaryWorkspace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scope:.
        /// </summary>
        public static string TagScopeHeaderLabel {
            get {
                return ResourceManager.GetString("TagScopeHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags:.
        /// </summary>
        public static string TagsHeaderLabel {
            get {
                return ResourceManager.GetString("TagsHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target:.
        /// </summary>
        public static string TargetHeaderLabel {
            get {
                return ResourceManager.GetString("TargetHeaderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not.
        /// </summary>
        public static string UnaryLogicKind_Not {
            get {
                return ResourceManager.GetString("UnaryLogicKind_Not", resourceCulture);
            }
        }
    }
}
