//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrystalEditor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class OurResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OurResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrystalEditor.OurResources", typeof(OurResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add &quot;{0}&quot; tag.
        /// </summary>
        internal static string AddTagLabel {
            get {
                return ResourceManager.GetString("AddTagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy &quot;{0}&quot; tag to &quot;{1}&quot;.
        /// </summary>
        internal static string CopyTagLabel {
            get {
                return ResourceManager.GetString("CopyTagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tag.
        /// </summary>
        internal static string NewAddTagLabel {
            get {
                return ResourceManager.GetString("NewAddTagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy tag.
        /// </summary>
        internal static string NewCopyTagLabel {
            get {
                return ResourceManager.GetString("NewCopyTagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove tag.
        /// </summary>
        internal static string NewRemoveTagLabel {
            get {
                return ResourceManager.GetString("NewRemoveTagLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Battle Effects.
        /// </summary>
        internal static string PostBattleEffectsNodeLabel {
            get {
                return ResourceManager.GetString("PostBattleEffectsNodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Result Effects.
        /// </summary>
        internal static string PostResultEffectsNodelLabel {
            get {
                return ResourceManager.GetString("PostResultEffectsNodelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post-Turn Effects.
        /// </summary>
        internal static string PostTurnEffectsNodeLabel {
            get {
                return ResourceManager.GetString("PostTurnEffectsNodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Battle Effects.
        /// </summary>
        internal static string PreBattleEffectsNodeLabel {
            get {
                return ResourceManager.GetString("PreBattleEffectsNodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-Result Effects.
        /// </summary>
        internal static string PreResultEffectsNodeLabel {
            get {
                return ResourceManager.GetString("PreResultEffectsNodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove &quot;{0}&quot; tag.
        /// </summary>
        internal static string RemoveTagLabel {
            get {
                return ResourceManager.GetString("RemoveTagLabel", resourceCulture);
            }
        }
    }
}
